[package]
name = "slpkg"
version = "0.1.0"
authors = ["Joel Depooter <joel.depooter@safe.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
flate2 = "1.0"
structopt = { version = "0.2", default-features = false }
zip = "0.5.0"
